{
  "openapi": "3.0.0",
  "info": {
    "version": "0.0.0",
    "title": "Example: basic with immutability"
  },
  "paths": {
    "/pets": {
      "get": {
        "operationId": "listPets",
        "tags": [
          "Pets"
        ],
        "summary": "List pets",
        "parameters": [
          {
            "name": "perPage",
            "description": "Per page",
            "schema": {
              "type": "string",
              "default": "20"
            },
            "in": "query",
            "required": false
          },
          {
            "name": "page",
            "description": "Page number",
            "schema": {
              "type": "string",
              "default": "1"
            },
            "in": "query",
            "required": false
          },
          {
            "name": "orderBy",
            "description": "Order by",
            "schema": {
              "type": "string"
            },
            "in": "query",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "List succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "pets": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/PetResponse"
                      }
                    },
                    "pages": {
                      "$ref": "#/components/schemas/PaginationResponse"
                    }
                  }
                },
                "examples": {
                  "pet1": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "pets": [
                        {
                          "name": "nisi"
                        },
                        {
                          "name": "omnis"
                        },
                        {
                          "name": "harum"
                        },
                        {
                          "name": "voluptates"
                        },
                        {
                          "name": "sequi"
                        },
                        {
                          "name": "natus"
                        },
                        {
                          "name": "velit"
                        },
                        {
                          "name": "quasi"
                        },
                        {
                          "name": "velit"
                        },
                        {
                          "name": "qui"
                        },
                        {
                          "name": "perferendis"
                        },
                        {
                          "name": "placeat"
                        },
                        {
                          "name": "enim"
                        },
                        {
                          "name": "enim"
                        },
                        {
                          "name": "aut"
                        },
                        {
                          "name": "autem"
                        },
                        {
                          "name": "neque"
                        },
                        {
                          "name": "incidunt"
                        },
                        {
                          "name": "pariatur"
                        },
                        {
                          "name": "quia"
                        }
                      ]
                    }
                  },
                  "pet2": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "pets": [
                        {
                          "name": "placeat"
                        },
                        {
                          "name": "dolor"
                        },
                        {
                          "name": "eos"
                        },
                        {
                          "name": "vel"
                        },
                        {
                          "name": "iste"
                        },
                        {
                          "name": "assumenda"
                        },
                        {
                          "name": "optio"
                        },
                        {
                          "name": "neque"
                        },
                        {
                          "name": "soluta"
                        },
                        {
                          "name": "ratione"
                        },
                        {
                          "name": "est"
                        },
                        {
                          "name": "perferendis"
                        },
                        {
                          "name": "in"
                        },
                        {
                          "name": "pariatur"
                        },
                        {
                          "name": "vel"
                        },
                        {
                          "name": "doloremque"
                        },
                        {
                          "name": "occaecati"
                        },
                        {
                          "name": "voluptatem"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "sed"
                        }
                      ]
                    }
                  },
                  "pet3": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "pets": [
                        {
                          "name": "maxime"
                        },
                        {
                          "name": "atque"
                        },
                        {
                          "name": "placeat"
                        },
                        {
                          "name": "cumque"
                        },
                        {
                          "name": "impedit"
                        },
                        {
                          "name": "id"
                        },
                        {
                          "name": "voluptates"
                        },
                        {
                          "name": "sed"
                        },
                        {
                          "name": "fugit"
                        },
                        {
                          "name": "commodi"
                        },
                        {
                          "name": "ut"
                        },
                        {
                          "name": "molestias"
                        },
                        {
                          "name": "doloremque"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "quaerat"
                        },
                        {
                          "name": "voluptatum"
                        },
                        {
                          "name": "perferendis"
                        },
                        {
                          "name": "quo"
                        },
                        {
                          "name": "earum"
                        },
                        {
                          "name": "corporis"
                        }
                      ]
                    }
                  },
                  "pet4": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "pets": [
                        {
                          "name": "vero"
                        },
                        {
                          "name": "dolores"
                        },
                        {
                          "name": "sapiente"
                        },
                        {
                          "name": "dolorem"
                        },
                        {
                          "name": "beatae"
                        },
                        {
                          "name": "laboriosam"
                        },
                        {
                          "name": "doloribus"
                        },
                        {
                          "name": "ea"
                        },
                        {
                          "name": "omnis"
                        },
                        {
                          "name": "voluptas"
                        },
                        {
                          "name": "eos"
                        },
                        {
                          "name": "praesentium"
                        },
                        {
                          "name": "quisquam"
                        },
                        {
                          "name": "modi"
                        },
                        {
                          "name": "fugiat"
                        },
                        {
                          "name": "placeat"
                        },
                        {
                          "name": "minus"
                        },
                        {
                          "name": "ut"
                        },
                        {
                          "name": "fugiat"
                        },
                        {
                          "name": "nulla"
                        }
                      ]
                    }
                  },
                  "pet5": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "pets": [
                        {
                          "name": "sit"
                        },
                        {
                          "name": "est"
                        },
                        {
                          "name": "sed"
                        },
                        {
                          "name": "quia"
                        },
                        {
                          "name": "assumenda"
                        },
                        {
                          "name": "animi"
                        },
                        {
                          "name": "vitae"
                        },
                        {
                          "name": "ipsum"
                        },
                        {
                          "name": "hic"
                        },
                        {
                          "name": "eveniet"
                        },
                        {
                          "name": "occaecati"
                        },
                        {
                          "name": "error"
                        },
                        {
                          "name": "repellendus"
                        },
                        {
                          "name": "ut"
                        },
                        {
                          "name": "sunt"
                        },
                        {
                          "name": "quos"
                        },
                        {
                          "name": "consequatur"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "voluptatem"
                        },
                        {
                          "name": "maiores"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createPet",
        "tags": [
          "Pets"
        ],
        "summary": "Create pet",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PetRequest"
              },
              "examples": {
                "pet1": {
                  "value": {
                    "name": "ut"
                  }
                },
                "pet2": {
                  "value": {
                    "name": "nulla"
                  }
                },
                "pet3": {
                  "value": {
                    "name": "reprehenderit"
                  }
                },
                "pet4": {
                  "value": {
                    "name": "incidunt"
                  }
                },
                "pet5": {
                  "value": {
                    "name": "molestiae"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "pet": {
                      "$ref": "#/components/schemas/PetResponse"
                    }
                  }
                },
                "examples": {
                  "pet1": {
                    "value": {
                      "pet": {
                        "name": "molestiae"
                      }
                    }
                  },
                  "pet2": {
                    "value": {
                      "pet": {
                        "name": "voluptate"
                      }
                    }
                  },
                  "pet3": {
                    "value": {
                      "pet": {
                        "name": "quae"
                      }
                    }
                  },
                  "pet4": {
                    "value": {
                      "pet": {
                        "name": "odit"
                      }
                    }
                  },
                  "pet5": {
                    "value": {
                      "pet": {
                        "name": "nesciunt"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/pets/{petId}": {
      "head": {
        "operationId": "checkPet",
        "tags": [
          "Pets"
        ],
        "summary": "Check pet",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "petId",
            "schema": {
              "type": "string"
            },
            "description": "Pet id"
          }
        ],
        "responses": {
          "200": {
            "description": "Check succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmptyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "get": {
        "operationId": "getPet",
        "tags": [
          "Pets"
        ],
        "summary": "Get pet",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "petId",
            "schema": {
              "type": "string"
            },
            "description": "Pet id"
          }
        ],
        "responses": {
          "200": {
            "description": "Get succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "pet": {
                      "$ref": "#/components/schemas/PetResponse"
                    }
                  }
                },
                "examples": {
                  "pet1": {
                    "value": {
                      "pet": {
                        "name": "reprehenderit"
                      }
                    }
                  },
                  "pet2": {
                    "value": {
                      "pet": {
                        "name": "aut"
                      }
                    }
                  },
                  "pet3": {
                    "value": {
                      "pet": {
                        "name": "sed"
                      }
                    }
                  },
                  "pet4": {
                    "value": {
                      "pet": {
                        "name": "fugit"
                      }
                    }
                  },
                  "pet5": {
                    "value": {
                      "pet": {
                        "name": "quia"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "deletePet",
        "tags": [
          "Pets"
        ],
        "summary": "Delete pet",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "petId",
            "schema": {
              "type": "string"
            },
            "description": "Pet id"
          }
        ],
        "responses": {
          "204": {
            "description": "Delete succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmptyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "EmptyResponse": {
        "type": "object"
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "code": {
            "type": "number",
            "readOnly": true
          },
          "message": {
            "type": "string",
            "readOnly": true
          },
          "status": {
            "type": "string",
            "readOnly": true
          },
          "details": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "readOnly": true
          }
        },
        "required": [
          "statusCode",
          "message"
        ]
      },
      "PaginationResponse": {
        "type": "object",
        "properties": {
          "firstPage": {
            "type": "number"
          },
          "lastPage": {
            "type": "number"
          },
          "nextPage": {
            "type": "number"
          },
          "prevPage": {
            "type": "number"
          }
        },
        "required": [
          "firstPage",
          "lastPage",
          "nextPage",
          "prevPage"
        ]
      },
      "PetResponse": {
        "properties": {
          "name": {
            "type": "string"
          }
        }
      },
      "PetRequest": {
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}