openapi: 3.0.0
info:
  version: 0.0.0
  title: 'Example: treeOf with belongsTo'
paths:
  /regions:
    get:
      operationId: listRegions
      tags:
        - Regions
      summary: List regions
      parameters:
        - name: pageSize
          description: Page size
          schema:
            type: integer
            format: int32
            default: 20
          in: query
          required: false
        - name: pageToken
          description: Page token
          schema:
            type: string
          in: query
          required: false
        - name: orderBy
          description: Order by
          schema:
            type: string
          in: query
          required: false
      responses:
        '200':
          description: List succeeded
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginationResponse'
                  - type: object
                    properties:
                      regions:
                        type: array
                        items:
                          $ref: '#/components/schemas/RegionResponse'
              examples:
                region1:
                  value:
                    nextPageToken: 7ddd6892-a486-489f-992f-aadb5691d507
                    regions:
                      - name: harum
                      - name: pariatur
                      - name: quidem
                      - name: et
                      - name: est
                      - name: in
                      - name: suscipit
                      - name: ut
                      - name: tempore
                      - name: ipsum
                      - name: sapiente
                      - name: similique
                      - name: dignissimos
                      - name: nemo
                      - name: exercitationem
                      - name: magni
                      - name: officia
                      - name: inventore
                      - name: enim
                      - name: repudiandae
                region2:
                  value:
                    nextPageToken: 3718519d-5aa7-4471-9214-25c0885d704d
                    regions:
                      - name: aut
                      - name: eveniet
                      - name: quia
                      - name: laudantium
                      - name: repellendus
                      - name: recusandae
                      - name: maiores
                      - name: commodi
                      - name: vel
                      - name: corrupti
                      - name: atque
                      - name: et
                      - name: ea
                      - name: pariatur
                      - name: voluptatem
                      - name: deleniti
                      - name: dolorum
                      - name: error
                      - name: ut
                      - name: sed
                region3:
                  value:
                    nextPageToken: 37996731-201f-4c8d-88cd-89508e6c9d33
                    regions:
                      - name: quibusdam
                      - name: odit
                      - name: occaecati
                      - name: ut
                      - name: placeat
                      - name: nemo
                      - name: aut
                      - name: necessitatibus
                      - name: illo
                      - name: officiis
                      - name: quos
                      - name: et
                      - name: qui
                      - name: rerum
                      - name: in
                      - name: suscipit
                      - name: reprehenderit
                      - name: alias
                      - name: repudiandae
                      - name: praesentium
                region4:
                  value:
                    nextPageToken: 2b9e673f-6623-4daf-b1c9-d9e41a2aff97
                    regions:
                      - name: officiis
                      - name: error
                      - name: quos
                      - name: culpa
                      - name: tempore
                      - name: voluptas
                      - name: vitae
                      - name: earum
                      - name: delectus
                      - name: inventore
                      - name: magni
                      - name: laudantium
                      - name: eaque
                      - name: nam
                      - name: velit
                      - name: consequatur
                      - name: veritatis
                      - name: magnam
                      - name: deserunt
                      - name: eveniet
                region5:
                  value:
                    nextPageToken: 50b1f4ab-faca-4465-ac34-aeb22847604b
                    regions:
                      - name: praesentium
                      - name: adipisci
                      - name: nihil
                      - name: rerum
                      - name: deserunt
                      - name: voluptate
                      - name: deserunt
                      - name: expedita
                      - name: cumque
                      - name: mollitia
                      - name: atque
                      - name: dolore
                      - name: autem
                      - name: corporis
                      - name: accusantium
                      - name: id
                      - name: aut
                      - name: nihil
                      - name: ut
                      - name: corrupti
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: createRegion
      tags:
        - Regions
      summary: Create region
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegionRequest'
            examples:
              region1:
                value:
                  name: accusamus
              region2:
                value:
                  name: aut
              region3:
                value:
                  name: est
              region4:
                value:
                  name: perspiciatis
              region5:
                value:
                  name: quos
      responses:
        '201':
          description: Create succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  region:
                    $ref: '#/components/schemas/RegionResponse'
              examples:
                region1:
                  value:
                    region:
                      name: saepe
                region2:
                  value:
                    region:
                      name: et
                region3:
                  value:
                    region:
                      name: quod
                region4:
                  value:
                    region:
                      name: culpa
                region5:
                  value:
                    region:
                      name: aut
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/regions/{regionId}':
    head:
      operationId: checkRegion
      tags:
        - Regions
      summary: Check region
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
      responses:
        '200':
          description: Check succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      operationId: getRegion
      tags:
        - Regions
      summary: Get region
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
      responses:
        '200':
          description: Get succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  region:
                    $ref: '#/components/schemas/RegionResponse'
              examples:
                region1:
                  value:
                    region:
                      name: veniam
                region2:
                  value:
                    region:
                      name: alias
                region3:
                  value:
                    region:
                      name: ducimus
                region4:
                  value:
                    region:
                      name: nostrum
                region5:
                  value:
                    region:
                      name: quisquam
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      operationId: replaceRegion
      tags:
        - Regions
      summary: Replace region
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegionRequest'
            examples:
              region1:
                value:
                  name: delectus
              region2:
                value:
                  name: expedita
              region3:
                value:
                  name: porro
              region4:
                value:
                  name: quia
              region5:
                value:
                  name: eaque
      responses:
        '200':
          description: Replace succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  region:
                    $ref: '#/components/schemas/RegionResponse'
              examples:
                region1:
                  value:
                    region:
                      name: quia
                region2:
                  value:
                    region:
                      name: repudiandae
                region3:
                  value:
                    region:
                      name: excepturi
                region4:
                  value:
                    region:
                      name: pariatur
                region5:
                  value:
                    region:
                      name: voluptatem
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      operationId: modifyRegion
      tags:
        - Regions
      summary: Modify region
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegionRequest'
            examples:
              region1:
                value:
                  name: eum
              region2:
                value:
                  name: consequuntur
              region3:
                value:
                  name: quos
              region4:
                value:
                  name: qui
              region5:
                value:
                  name: ut
      responses:
        '200':
          description: Modify succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  region:
                    $ref: '#/components/schemas/RegionResponse'
              examples:
                region1:
                  value:
                    region:
                      name: accusamus
                region2:
                  value:
                    region:
                      name: sit
                region3:
                  value:
                    region:
                      name: quia
                region4:
                  value:
                    region:
                      name: non
                region5:
                  value:
                    region:
                      name: tempore
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      operationId: deleteRegion
      tags:
        - Regions
      summary: Delete region
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
      responses:
        '204':
          description: Delete succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/regions/{regionId}/groups':
    get:
      operationId: listRegionGroups
      tags:
        - Regions
      summary: List region groups
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - name: pageSize
          description: Page size
          schema:
            type: integer
            format: int32
            default: 20
          in: query
          required: false
        - name: pageToken
          description: Page token
          schema:
            type: string
          in: query
          required: false
        - name: orderBy
          description: Order by
          schema:
            type: string
          in: query
          required: false
      responses:
        '200':
          description: List succeeded
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginationResponse'
                  - type: object
                    properties:
                      groups:
                        type: array
                        items:
                          $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    nextPageToken: 605d0a31-4bb1-4609-a906-a26b919e1898
                    groups:
                      - name: et
                      - name: nihil
                      - name: temporibus
                      - name: animi
                      - name: ullam
                      - name: consequuntur
                      - name: qui
                      - name: aut
                      - name: repellat
                      - name: magni
                      - name: ut
                      - name: consectetur
                      - name: et
                      - name: facilis
                      - name: sint
                      - name: sapiente
                      - name: non
                      - name: et
                      - name: ratione
                      - name: est
                group2:
                  value:
                    nextPageToken: 4874d8ba-d419-443a-a304-64e2558b80c6
                    groups:
                      - name: quia
                      - name: quaerat
                      - name: eaque
                      - name: veritatis
                      - name: quasi
                      - name: placeat
                      - name: nam
                      - name: beatae
                      - name: non
                      - name: earum
                      - name: sunt
                      - name: excepturi
                      - name: aut
                      - name: qui
                      - name: sit
                      - name: distinctio
                      - name: eligendi
                      - name: excepturi
                      - name: laborum
                      - name: occaecati
                group3:
                  value:
                    nextPageToken: 5152e1cf-ad5e-4175-8304-78a9aac4987c
                    groups:
                      - name: et
                      - name: maiores
                      - name: et
                      - name: repellendus
                      - name: placeat
                      - name: eaque
                      - name: consectetur
                      - name: vel
                      - name: minima
                      - name: et
                      - name: tenetur
                      - name: iste
                      - name: quaerat
                      - name: cumque
                      - name: repellendus
                      - name: praesentium
                      - name: quibusdam
                      - name: eveniet
                      - name: voluptates
                      - name: et
                group4:
                  value:
                    nextPageToken: 22f1128d-4897-4cdb-8b75-95229f555b28
                    groups:
                      - name: nulla
                      - name: sunt
                      - name: consequatur
                      - name: tempore
                      - name: ex
                      - name: id
                      - name: voluptatum
                      - name: mollitia
                      - name: illum
                      - name: nihil
                      - name: quaerat
                      - name: voluptate
                      - name: qui
                      - name: debitis
                      - name: est
                      - name: aspernatur
                      - name: minus
                      - name: laborum
                      - name: unde
                      - name: voluptas
                group5:
                  value:
                    nextPageToken: 6bb1729d-5d33-4304-b9a2-f81b9b0ebe2f
                    groups:
                      - name: voluptates
                      - name: fuga
                      - name: sint
                      - name: modi
                      - name: qui
                      - name: ut
                      - name: molestiae
                      - name: nulla
                      - name: in
                      - name: voluptate
                      - name: reiciendis
                      - name: molestias
                      - name: omnis
                      - name: voluptatem
                      - name: ea
                      - name: earum
                      - name: dignissimos
                      - name: beatae
                      - name: voluptates
                      - name: non
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: createRegionGroup
      tags:
        - Regions
      summary: Create region group
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
            examples:
              group1:
                value:
                  name: tenetur
              group2:
                value:
                  name: incidunt
              group3:
                value:
                  name: pariatur
              group4:
                value:
                  name: voluptates
              group5:
                value:
                  name: quia
      responses:
        '201':
          description: Create succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: eum
                group2:
                  value:
                    group:
                      name: error
                group3:
                  value:
                    group:
                      name: voluptates
                group4:
                  value:
                    group:
                      name: rem
                group5:
                  value:
                    group:
                      name: dolor
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/regions/{regionId}/groups/{groupId}':
    head:
      operationId: checkRegionGroup
      tags:
        - Regions
      summary: Check region group
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
      responses:
        '200':
          description: Check succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      operationId: getRegionGroup
      tags:
        - Regions
      summary: Get region group
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
      responses:
        '200':
          description: Get succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: voluptatem
                group2:
                  value:
                    group:
                      name: eos
                group3:
                  value:
                    group:
                      name: non
                group4:
                  value:
                    group:
                      name: dicta
                group5:
                  value:
                    group:
                      name: esse
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      operationId: replaceRegionGroup
      tags:
        - Regions
      summary: Replace region group
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
            examples:
              group1:
                value:
                  name: ipsa
              group2:
                value:
                  name: ut
              group3:
                value:
                  name: ipsum
              group4:
                value:
                  name: quo
              group5:
                value:
                  name: repudiandae
      responses:
        '200':
          description: Replace succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: vel
                group2:
                  value:
                    group:
                      name: ut
                group3:
                  value:
                    group:
                      name: ea
                group4:
                  value:
                    group:
                      name: doloribus
                group5:
                  value:
                    group:
                      name: omnis
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      operationId: modifyRegionGroup
      tags:
        - Regions
      summary: Modify region group
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
            examples:
              group1:
                value:
                  name: sint
              group2:
                value:
                  name: sit
              group3:
                value:
                  name: excepturi
              group4:
                value:
                  name: et
              group5:
                value:
                  name: voluptatem
      responses:
        '200':
          description: Modify succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: deserunt
                group2:
                  value:
                    group:
                      name: sunt
                group3:
                  value:
                    group:
                      name: animi
                group4:
                  value:
                    group:
                      name: est
                group5:
                  value:
                    group:
                      name: culpa
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      operationId: deleteRegionGroup
      tags:
        - Regions
      summary: Delete region group
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
      responses:
        '204':
          description: Delete succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/regions/{regionId}/groups/{groupId}/subgroups':
    get:
      operationId: listRegionGroupSubgroups
      tags:
        - Regions
      summary: List region group subgroups
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
        - name: pageSize
          description: Page size
          schema:
            type: integer
            format: int32
            default: 20
          in: query
          required: false
        - name: pageToken
          description: Page token
          schema:
            type: string
          in: query
          required: false
        - name: orderBy
          description: Order by
          schema:
            type: string
          in: query
          required: false
      responses:
        '200':
          description: List succeeded
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/PaginationResponse'
                  - type: object
                    properties:
                      groups:
                        type: array
                        items:
                          $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    nextPageToken: fa793cac-7921-4edc-9ab1-f9af009392ce
                    groups:
                      - name: rerum
                      - name: enim
                      - name: id
                      - name: dolorum
                      - name: ex
                      - name: dolor
                      - name: libero
                      - name: molestiae
                      - name: adipisci
                      - name: pariatur
                      - name: et
                      - name: doloribus
                      - name: sapiente
                      - name: vel
                      - name: maiores
                      - name: est
                      - name: quasi
                      - name: quia
                      - name: quisquam
                      - name: doloribus
                group2:
                  value:
                    nextPageToken: 21c12d20-ca34-4545-9a15-d02867f5c1f9
                    groups:
                      - name: hic
                      - name: non
                      - name: architecto
                      - name: fugit
                      - name: quis
                      - name: sint
                      - name: sint
                      - name: dolores
                      - name: voluptate
                      - name: ad
                      - name: architecto
                      - name: iste
                      - name: quasi
                      - name: asperiores
                      - name: repudiandae
                      - name: dolor
                      - name: ex
                      - name: quisquam
                      - name: voluptas
                      - name: aspernatur
                group3:
                  value:
                    nextPageToken: 9ce2f0ab-d69d-43a1-9c57-61daa6998106
                    groups:
                      - name: vel
                      - name: sed
                      - name: vel
                      - name: eum
                      - name: aut
                      - name: fuga
                      - name: ipsum
                      - name: laudantium
                      - name: est
                      - name: aut
                      - name: id
                      - name: aut
                      - name: aut
                      - name: praesentium
                      - name: ab
                      - name: quis
                      - name: illum
                      - name: nesciunt
                      - name: itaque
                      - name: quo
                group4:
                  value:
                    nextPageToken: 28e7306b-ab05-4a62-b7a1-db5a2873180d
                    groups:
                      - name: exercitationem
                      - name: eaque
                      - name: perferendis
                      - name: quibusdam
                      - name: sed
                      - name: repudiandae
                      - name: voluptatibus
                      - name: molestiae
                      - name: porro
                      - name: labore
                      - name: voluptatem
                      - name: vel
                      - name: voluptatum
                      - name: illo
                      - name: dicta
                      - name: ab
                      - name: nihil
                      - name: incidunt
                      - name: non
                      - name: facilis
                group5:
                  value:
                    nextPageToken: 582bcdb0-8f37-4b73-80ec-bcd5e43be2c1
                    groups:
                      - name: et
                      - name: voluptatem
                      - name: non
                      - name: ut
                      - name: ea
                      - name: sunt
                      - name: provident
                      - name: eos
                      - name: cum
                      - name: hic
                      - name: rerum
                      - name: eum
                      - name: explicabo
                      - name: minima
                      - name: ipsum
                      - name: animi
                      - name: veritatis
                      - name: officiis
                      - name: recusandae
                      - name: sed
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: createRegionGroupSubgroup
      tags:
        - Regions
      summary: Create region group subgroup
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
            examples:
              group1:
                value:
                  name: culpa
              group2:
                value:
                  name: dolore
              group3:
                value:
                  name: officia
              group4:
                value:
                  name: pariatur
              group5:
                value:
                  name: esse
      responses:
        '201':
          description: Create succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: dignissimos
                group2:
                  value:
                    group:
                      name: porro
                group3:
                  value:
                    group:
                      name: unde
                group4:
                  value:
                    group:
                      name: amet
                group5:
                  value:
                    group:
                      name: distinctio
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/regions/{regionId}/groups/{groupId}/subgroups/{subgroupId}':
    head:
      operationId: checkRegionGroupSubgroup
      tags:
        - Regions
      summary: Check region group subgroup
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
        - in: path
          required: true
          name: subgroupId
          schema:
            type: string
          description: Subgroup id
      responses:
        '200':
          description: Check succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      operationId: getRegionGroupSubgroup
      tags:
        - Regions
      summary: Get region group subgroup
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
        - in: path
          required: true
          name: subgroupId
          schema:
            type: string
          description: Subgroup id
      responses:
        '200':
          description: Get succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: et
                group2:
                  value:
                    group:
                      name: est
                group3:
                  value:
                    group:
                      name: non
                group4:
                  value:
                    group:
                      name: debitis
                group5:
                  value:
                    group:
                      name: soluta
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      operationId: replaceRegionGroupSubgroup
      tags:
        - Regions
      summary: Replace region group subgroup
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
        - in: path
          required: true
          name: subgroupId
          schema:
            type: string
          description: Subgroup id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
            examples:
              group1:
                value:
                  name: et
              group2:
                value:
                  name: ut
              group3:
                value:
                  name: et
              group4:
                value:
                  name: eos
              group5:
                value:
                  name: ut
      responses:
        '200':
          description: Replace succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: blanditiis
                group2:
                  value:
                    group:
                      name: odit
                group3:
                  value:
                    group:
                      name: aut
                group4:
                  value:
                    group:
                      name: consequatur
                group5:
                  value:
                    group:
                      name: rerum
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      operationId: modifyRegionGroupSubgroup
      tags:
        - Regions
      summary: Modify region group subgroup
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
        - in: path
          required: true
          name: subgroupId
          schema:
            type: string
          description: Subgroup id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
            examples:
              group1:
                value:
                  name: aliquam
              group2:
                value:
                  name: ipsum
              group3:
                value:
                  name: quia
              group4:
                value:
                  name: dicta
              group5:
                value:
                  name: dolore
      responses:
        '200':
          description: Modify succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    $ref: '#/components/schemas/GroupResponse'
              examples:
                group1:
                  value:
                    group:
                      name: voluptas
                group2:
                  value:
                    group:
                      name: fugiat
                group3:
                  value:
                    group:
                      name: rerum
                group4:
                  value:
                    group:
                      name: id
                group5:
                  value:
                    group:
                      name: deleniti
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      operationId: deleteRegionGroupSubgroup
      tags:
        - Regions
      summary: Delete region group subgroup
      parameters:
        - in: path
          required: true
          name: regionId
          schema:
            type: string
          description: Region id
        - in: path
          required: true
          name: groupId
          schema:
            type: string
          description: Group id
        - in: path
          required: true
          name: subgroupId
          schema:
            type: string
          description: Subgroup id
      responses:
        '204':
          description: Delete succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    EmptyResponse:
      type: object
    ErrorResponse:
      type: object
      properties:
        code:
          type: number
          readOnly: true
        message:
          type: string
          readOnly: true
        status:
          type: string
          readOnly: true
        details:
          type: array
          items:
            type: string
          readOnly: true
      required:
        - statusCode
        - message
    PaginationResponse:
      type: object
      properties:
        nextPageToken:
          type: string
          format: uuid
      required:
        - nextPageToken
    RegionResponse:
      properties:
        name:
          type: string
    RegionRequest:
      properties:
        name:
          type: string
    GroupResponse:
      properties:
        name:
          type: string
    GroupRequest:
      properties:
        name:
          type: string
