{
  "openapi": "3.0.0",
  "info": {
    "version": "0.0.0",
    "title": "Example: users"
  },
  "paths": {
    "/users": {
      "get": {
        "operationId": "listUsers",
        "tags": [
          "Users"
        ],
        "summary": "List users",
        "parameters": [
          {
            "name": "perPage",
            "description": "Per page",
            "schema": {
              "type": "string",
              "default": "20"
            },
            "in": "query",
            "required": false
          },
          {
            "name": "page",
            "description": "Page number",
            "schema": {
              "type": "string",
              "default": "1"
            },
            "in": "query",
            "required": false
          },
          {
            "name": "orderBy",
            "description": "Order by",
            "schema": {
              "type": "string"
            },
            "in": "query",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "List succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "users": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/UserResponse"
                      }
                    },
                    "pages": {
                      "$ref": "#/components/schemas/PaginationResponse"
                    }
                  }
                },
                "examples": {
                  "user1": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "users": [
                        {
                          "name": "magni"
                        },
                        {
                          "name": "dolorem"
                        },
                        {
                          "name": "soluta"
                        },
                        {
                          "name": "dolore"
                        },
                        {
                          "name": "voluptas"
                        },
                        {
                          "name": "aliquid"
                        },
                        {
                          "name": "ullam"
                        },
                        {
                          "name": "culpa"
                        },
                        {
                          "name": "amet"
                        },
                        {
                          "name": "est"
                        },
                        {
                          "name": "ipsum"
                        },
                        {
                          "name": "repellendus"
                        },
                        {
                          "name": "est"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "esse"
                        },
                        {
                          "name": "sunt"
                        },
                        {
                          "name": "repudiandae"
                        },
                        {
                          "name": "nesciunt"
                        },
                        {
                          "name": "laborum"
                        },
                        {
                          "name": "quas"
                        }
                      ]
                    }
                  },
                  "user2": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "users": [
                        {
                          "name": "consequatur"
                        },
                        {
                          "name": "dolores"
                        },
                        {
                          "name": "molestiae"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "ut"
                        },
                        {
                          "name": "id"
                        },
                        {
                          "name": "in"
                        },
                        {
                          "name": "sed"
                        },
                        {
                          "name": "iure"
                        },
                        {
                          "name": "consectetur"
                        },
                        {
                          "name": "qui"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "quam"
                        },
                        {
                          "name": "laboriosam"
                        },
                        {
                          "name": "consequatur"
                        },
                        {
                          "name": "nulla"
                        },
                        {
                          "name": "iusto"
                        },
                        {
                          "name": "voluptates"
                        },
                        {
                          "name": "facilis"
                        },
                        {
                          "name": "optio"
                        }
                      ]
                    }
                  },
                  "user3": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "users": [
                        {
                          "name": "deserunt"
                        },
                        {
                          "name": "veritatis"
                        },
                        {
                          "name": "aut"
                        },
                        {
                          "name": "aut"
                        },
                        {
                          "name": "pariatur"
                        },
                        {
                          "name": "natus"
                        },
                        {
                          "name": "non"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "nemo"
                        },
                        {
                          "name": "maxime"
                        },
                        {
                          "name": "placeat"
                        },
                        {
                          "name": "quae"
                        },
                        {
                          "name": "accusantium"
                        },
                        {
                          "name": "laborum"
                        },
                        {
                          "name": "est"
                        },
                        {
                          "name": "optio"
                        },
                        {
                          "name": "adipisci"
                        },
                        {
                          "name": "maiores"
                        },
                        {
                          "name": "aspernatur"
                        },
                        {
                          "name": "quae"
                        }
                      ]
                    }
                  },
                  "user4": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "users": [
                        {
                          "name": "totam"
                        },
                        {
                          "name": "praesentium"
                        },
                        {
                          "name": "nemo"
                        },
                        {
                          "name": "incidunt"
                        },
                        {
                          "name": "voluptas"
                        },
                        {
                          "name": "ratione"
                        },
                        {
                          "name": "quas"
                        },
                        {
                          "name": "eos"
                        },
                        {
                          "name": "eius"
                        },
                        {
                          "name": "qui"
                        },
                        {
                          "name": "dicta"
                        },
                        {
                          "name": "optio"
                        },
                        {
                          "name": "doloremque"
                        },
                        {
                          "name": "quod"
                        },
                        {
                          "name": "eligendi"
                        },
                        {
                          "name": "minima"
                        },
                        {
                          "name": "inventore"
                        },
                        {
                          "name": "ut"
                        },
                        {
                          "name": "est"
                        },
                        {
                          "name": "beatae"
                        }
                      ]
                    }
                  },
                  "user5": {
                    "value": {
                      "pagination": {
                        "firstPage": "1",
                        "lastPage": "10",
                        "nextPage": "2",
                        "prevPage": "1"
                      },
                      "users": [
                        {
                          "name": "occaecati"
                        },
                        {
                          "name": "quo"
                        },
                        {
                          "name": "expedita"
                        },
                        {
                          "name": "nostrum"
                        },
                        {
                          "name": "et"
                        },
                        {
                          "name": "quis"
                        },
                        {
                          "name": "dolor"
                        },
                        {
                          "name": "qui"
                        },
                        {
                          "name": "quia"
                        },
                        {
                          "name": "nisi"
                        },
                        {
                          "name": "consequatur"
                        },
                        {
                          "name": "nihil"
                        },
                        {
                          "name": "eos"
                        },
                        {
                          "name": "nisi"
                        },
                        {
                          "name": "eum"
                        },
                        {
                          "name": "incidunt"
                        },
                        {
                          "name": "rerum"
                        },
                        {
                          "name": "ab"
                        },
                        {
                          "name": "quo"
                        },
                        {
                          "name": "velit"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createUser",
        "tags": [
          "Users"
        ],
        "summary": "Create user",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRequest"
              },
              "examples": {
                "user1": {
                  "value": {
                    "name": "asperiores"
                  }
                },
                "user2": {
                  "value": {
                    "name": "excepturi"
                  }
                },
                "user3": {
                  "value": {
                    "name": "aut"
                  }
                },
                "user4": {
                  "value": {
                    "name": "esse"
                  }
                },
                "user5": {
                  "value": {
                    "name": "consequatur"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/UserResponse"
                    }
                  }
                },
                "examples": {
                  "user1": {
                    "value": {
                      "user": {
                        "name": "accusantium"
                      }
                    }
                  },
                  "user2": {
                    "value": {
                      "user": {
                        "name": "ut"
                      }
                    }
                  },
                  "user3": {
                    "value": {
                      "user": {
                        "name": "autem"
                      }
                    }
                  },
                  "user4": {
                    "value": {
                      "user": {
                        "name": "beatae"
                      }
                    }
                  },
                  "user5": {
                    "value": {
                      "user": {
                        "name": "quia"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "head": {
        "operationId": "checkUser",
        "tags": [
          "Users"
        ],
        "summary": "Check user",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "description": "User id"
          }
        ],
        "responses": {
          "200": {
            "description": "Check succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmptyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "get": {
        "operationId": "getUser",
        "tags": [
          "Users"
        ],
        "summary": "Get user",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "description": "User id"
          }
        ],
        "responses": {
          "200": {
            "description": "Get succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/UserResponse"
                    }
                  }
                },
                "examples": {
                  "user1": {
                    "value": {
                      "user": {
                        "name": "ratione"
                      }
                    }
                  },
                  "user2": {
                    "value": {
                      "user": {
                        "name": "minima"
                      }
                    }
                  },
                  "user3": {
                    "value": {
                      "user": {
                        "name": "consequatur"
                      }
                    }
                  },
                  "user4": {
                    "value": {
                      "user": {
                        "name": "non"
                      }
                    }
                  },
                  "user5": {
                    "value": {
                      "user": {
                        "name": "suscipit"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "put": {
        "operationId": "replaceUser",
        "tags": [
          "Users"
        ],
        "summary": "Replace user",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "description": "User id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRequest"
              },
              "examples": {
                "user1": {
                  "value": {
                    "name": "commodi"
                  }
                },
                "user2": {
                  "value": {
                    "name": "adipisci"
                  }
                },
                "user3": {
                  "value": {
                    "name": "dignissimos"
                  }
                },
                "user4": {
                  "value": {
                    "name": "nihil"
                  }
                },
                "user5": {
                  "value": {
                    "name": "veritatis"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Replace succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/UserResponse"
                    }
                  }
                },
                "examples": {
                  "user1": {
                    "value": {
                      "user": {
                        "name": "itaque"
                      }
                    }
                  },
                  "user2": {
                    "value": {
                      "user": {
                        "name": "sunt"
                      }
                    }
                  },
                  "user3": {
                    "value": {
                      "user": {
                        "name": "ipsam"
                      }
                    }
                  },
                  "user4": {
                    "value": {
                      "user": {
                        "name": "harum"
                      }
                    }
                  },
                  "user5": {
                    "value": {
                      "user": {
                        "name": "impedit"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "patch": {
        "operationId": "updateUser",
        "tags": [
          "Users"
        ],
        "summary": "Update user",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "description": "User id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRequest"
              },
              "examples": {
                "user1": {
                  "value": {
                    "name": "autem"
                  }
                },
                "user2": {
                  "value": {
                    "name": "qui"
                  }
                },
                "user3": {
                  "value": {
                    "name": "est"
                  }
                },
                "user4": {
                  "value": {
                    "name": "voluptas"
                  }
                },
                "user5": {
                  "value": {
                    "name": "adipisci"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Update succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/UserResponse"
                    }
                  }
                },
                "examples": {
                  "user1": {
                    "value": {
                      "user": {
                        "name": "alias"
                      }
                    }
                  },
                  "user2": {
                    "value": {
                      "user": {
                        "name": "nihil"
                      }
                    }
                  },
                  "user3": {
                    "value": {
                      "user": {
                        "name": "est"
                      }
                    }
                  },
                  "user4": {
                    "value": {
                      "user": {
                        "name": "aliquam"
                      }
                    }
                  },
                  "user5": {
                    "value": {
                      "user": {
                        "name": "quam"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "deleteUser",
        "tags": [
          "Users"
        ],
        "summary": "Delete user",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "name": "userId",
            "schema": {
              "type": "string"
            },
            "description": "User id"
          }
        ],
        "responses": {
          "204": {
            "description": "Delete succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmptyResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "operationId": "getUserAsUser",
        "tags": [
          "User"
        ],
        "summary": "Get user for user",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Get succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "$ref": "#/components/schemas/UserResponse"
                    }
                  }
                },
                "examples": {
                  "user1": {
                    "value": {
                      "user": {
                        "name": "omnis"
                      }
                    }
                  },
                  "user2": {
                    "value": {
                      "user": {
                        "name": "itaque"
                      }
                    }
                  },
                  "user3": {
                    "value": {
                      "user": {
                        "name": "repellat"
                      }
                    }
                  },
                  "user4": {
                    "value": {
                      "user": {
                        "name": "doloremque"
                      }
                    }
                  },
                  "user5": {
                    "value": {
                      "user": {
                        "name": "fuga"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "EmptyResponse": {
        "type": "object"
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "code": {
            "type": "number",
            "readOnly": true
          },
          "message": {
            "type": "string",
            "readOnly": true
          },
          "status": {
            "type": "string",
            "readOnly": true
          },
          "details": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "readOnly": true
          }
        },
        "required": [
          "statusCode",
          "message"
        ]
      },
      "PaginationResponse": {
        "type": "object",
        "properties": {
          "firstPage": {
            "type": "number"
          },
          "lastPage": {
            "type": "number"
          },
          "nextPage": {
            "type": "number"
          },
          "prevPage": {
            "type": "number"
          }
        },
        "required": [
          "firstPage",
          "lastPage",
          "nextPage",
          "prevPage"
        ]
      },
      "UserResponse": {
        "properties": {
          "name": {
            "type": "string"
          }
        }
      },
      "UserRequest": {
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}